# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Start_pushButton.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.Start_pushButton.setObjectName("Start_pushButton")
        self.State_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.State_textBrowser.setGeometry(QtCore.QRect(120, 20, 251, 91))
        self.State_textBrowser.setObjectName("State_textBrowser")
        self.Refresh_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh_pushButton.setGeometry(QtCore.QRect(20, 70, 81, 41))
        self.Refresh_pushButton.setObjectName("Refresh_pushButton")
        self.State_pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.State_pushButton1.setGeometry(QtCore.QRect(30, 140, 103, 71))
        self.State_pushButton1.setIconSize(QtCore.QSize(20, 20))
        self.State_pushButton1.setCheckable(False)
        self.State_pushButton1.setObjectName("State_pushButton1")
        self.Stop_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_pushButton.setGeometry(QtCore.QRect(390, 20, 81, 41))
        self.Stop_pushButton.setObjectName("Stop_pushButton")
        self.State_pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.State_pushButton2.setGeometry(QtCore.QRect(190, 140, 103, 71))
        self.State_pushButton2.setObjectName("State_pushButton2")
        self.State_pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.State_pushButton3.setGeometry(QtCore.QRect(350, 140, 103, 71))
        self.State_pushButton3.setObjectName("State_pushButton3")
        self.State_pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.State_pushButton4.setGeometry(QtCore.QRect(30, 240, 103, 71))
        self.State_pushButton4.setObjectName("State_pushButton4")
        self.State_pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.State_pushButton5.setGeometry(QtCore.QRect(190, 240, 103, 71))
        self.State_pushButton5.setObjectName("State_pushButton5")
        self.State_pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.State_pushButton6.setGeometry(QtCore.QRect(350, 240, 103, 71))
        self.State_pushButton6.setObjectName("State_pushButton6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start_pushButton.setText(_translate("MainWindow", "开始"))
        self.Refresh_pushButton.setText(_translate("MainWindow", "刷新"))
        self.State_pushButton1.setText(_translate("MainWindow", "State1"))
        self.Stop_pushButton.setText(_translate("MainWindow", "停止"))
        self.State_pushButton2.setText(_translate("MainWindow", "State2"))
        self.State_pushButton3.setText(_translate("MainWindow", "State3"))
        self.State_pushButton4.setText(_translate("MainWindow", "State4"))
        self.State_pushButton5.setText(_translate("MainWindow", "State5"))
        self.State_pushButton6.setText(_translate("MainWindow", "State6"))
